= AsciiDoctor example
:toc:
:sourceDir: src/main/java

== Very useful features

=== Source code listings

Source code listings can be especially useful for outlining some specific code.

----
    private String name; <1>
    private int age; <2>
    private String city; <3>
----
<1> This is the name field
<2> ...
<3> ...

.Usage:
----

 ----
 private String name; \<1>
 private int age; \<2>
 private String city; \<3>
 ----
 <1>This is the name field +
 <2>... +
 <3>... +
----

=== Including real source code
Always up-tp-date source code! +
Includes code snippets corresponding to source code referenced.

.Include the whole file
----
 [source,java]
 ----
 include::path/to/your/file.java[]
 ----
----

You can also define 'tags' in your file to only include the specified tag. +
.Include only parts of it

.Person.java
[source,java]
----
// tag::fields[]
private String name;
private int age;
private String city;
// end::fields[]

public Person() {
}
...
----
.Only include parts of code
----
[source,java]
 ----
 include::path/to/your/file.java[tags=fields] <1>
 ----
----
<1> `[tags=fields]` tells asciidoctor to only include code with that tag

=== Diagrams

`Asciidoctor Diagram is a set of Asciidoctor extensions that enable you to add diagrams,
which you describe using plain text, to your AsciiDoc document.`
- https://asciidoctor.org/docs/asciidoctor-diagram/

.PlantUML diagram
[plantuml, diagram-classes]
....
Class01 "1" *-- "many" Class02 : contains

Class03 o-- Class04 : aggregation

Class05 --> "1" Class06
....

.Code behind:
----
[plantuml, diagram-classes] <1> <2>
....
Class01 "1" *-- "many" Class02 : contains

Class03 o-- Class04 : aggregation

Class05 --> "1" Class06
....
----
<1> Diagram type, in this case it is https://plantuml.com/de/[PlantUML]
<2> Name of the generated file (target)

It can happen that the diagram is unable to render, because it is missing some
libraries. In that case download http://www.graphviz.org/[Graphviz] and add it to your `PATH`

If it's still not working, maybe adding the path to your graphviz manually in your plugin config (pom.xml) might help:

.pom.xml
[source,xml]
----
<plugin>
    <groupId>org.asciidoctor</groupId>
    <artifactId>asciidoctor-maven-plugin</artifactId>
    ...
    <configuration>
        <attributes>
            <graphvizdot>/PATH/TO/Graphviz/bin/dot</graphvizdot>
        </attributes>
        ...
----


https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoctor-diagram-example[Example: How to use the maven plugin with diagrams]

== AsciiDoctor Maven-Plugin

Adding the AsciiDoctor Maven-Plugin to the plugins in the `pom.xml`
[source,xml]
----
    <plugin>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctor-maven-plugin</artifactId>
            <version>${asciidoctor.maven.plugin.version}</version>
    </plugin>
----
Here it is configured to generate a HTML file (= convert the `README.adoc`)
The dependency `asciidoctorj-diagram` is only required when rendering a diagram (PlantUML, Graphviz, ...)
[source,xml]
----
include::pom.xml[tags=plugin]
----


== AsciiDoctor via command line

.Prerequisites
* Ruby with the RubyGems package manager
** Ruby DevelopmentKit (If not already included)
* AsciiDoctor(Ruby Gem)

Installation is shown below.

=== Installation
Ruby installation on Windows with the Chocolatey or the RubyInstaller.

Install Ruby::
https://chocolatey.org/[Chocolatey]:
--
 $ choco install ruby
--
The RubyInstaller can be found https://rubyinstaller.org/downloads/[**here**].

Check installation
--
 $ ruby -v
 ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]
--
Get DevelopmentKit (if not already installed)::
The DevelopmentKit is needed for RubyGems(Package Manager)
--
 $ ridk install
--

Install Gems::
--
 $ gems install asciidoctor
--
Check installation
--
 $ asciidoctor --version
Asciidoctor 2.0.10 [https://asciidoctor.org]
--

=== Usage

Convert an AsciiDoc file to HTML
(Default converter is HTML5)

 $ asciidoctor mysample.adoc

This creates the file `mysample.html` in the same directory.

It is also possible to select an output file. +
For example, when we have a `index.html`, we can define the output file for the asciidoctor converter with the **-o** flag:

 $ asciidoctor mysample.adoc -o index.html

The *-o* flag sets the output target.


The complete manual for commands can be found  https://asciidoctor.org/man/asciidoctor/[**here**]. +

== Asciidoc Editor (AsciidocFx)
Asciidoc FX is a book / document editor to build PDF, Epub, Mobi and HTML books, documents and slides.

.Some of the featues are:
* Real-Time Preview
* Creating PDF, HTML, Docbook, ...
* Many Extentions (PlantUML, JavaFX)

https://github.com/asciidocfx/AsciidocFX/releases[Download]


== GitHub Pages with AsciiDoc

Currently, Github Pages cannot render an .adoc (AsciiDoc) file.
To use GitHub Pages with AsciiDoc files we have to convert the adoc files to HTML files. This can simply be done with the command line, see <<Usage>>.


== Links
* https://asciidoctor.org/[Official AsciiDoctor Page]
* https://asciidoctor.org/docs/asciidoctor-diagram/[AsciiDoctor Diagrams]
** https://asciidoctor.org/news/2014/02/18/plain-text-diagrams-in-asciidoctor/[Blog]
** https://plantuml.com/de/[PlantUML]
** http://www.graphviz.org/[Graphviz]
* https://asciidoctor.org/docs/asciidoctor-maven-plugin/[AsciiDoctor Maven-Plugin documentation]
** https://github.com/asciidoctor/asciidoctor-maven-examples[Maven-Plugin examples]
** https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoctor-diagram-example[Using diagrams]
* https://www.youtube.com/watch?v=MyhiD65qaUI[Quick video overview of AsciiDoctor]
* https://asciidoctor.org/docs/convert-documents/[How to convert adoc files]
* https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Cheatsheet (Syntax quick reference)]
* https://www.asciidocfx.com/[AsciidocFx (AsciidocFx)]
* https://pages.github.com/[GitHub Pages]




