= AsciiDoctor example
:toc: right 

== AsciiDoctor via command line

.Prerequisites
* Ruby with the RubyGems package manager
** Ruby DevelopmentKit (If not already included)
* AsciiDoctor(Ruby Gem)

Installation is shown below.

=== Installation
Ruby installation on Windows with the Chocolatey or the RubyInstaller.

Install Ruby:: 
https://chocolatey.org/[Chocolatey]:
--
 $ choco install ruby
--
The RubyInstaller can be found https://rubyinstaller.org/downloads/[**here**]. 

Check installation
--
 $ ruby -v
 ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]
--
Get DevelopmentKit (if not already installed)::
The DevelopmentKit is needed for RubyGems(Package Manager)
--
 $ ridk install
--

Install Gems::
--
 $ gems install asciidoctor
--
Check installation
--
 $ asciidoctor --version
Asciidoctor 2.0.10 [https://asciidoctor.org]
--

=== Usage

Convert an AsciiDoc file to HTML
(Default converter is HTML5)

 $ asciidoctor mysample.adoc

This creates the file `mysample.html` in the same directory.

It is also possible to select an output file. +
For example, when we have a `index.html`, we can define the output file for the asciidoctor converter with the **-o** flag:

 $ asciidoctor mysample.adoc -o index.html

The *-o* flag sets the output target.


The complete manual for commands can be found  https://asciidoctor.org/man/asciidoctor/[**here**]. +

== Asciidoc Editor (AsciidocFx)
Asciidoc FX is a book / document editor to build PDF, Epub, Mobi and HTML books, documents and slides. 

.Some of the featues are:
* Real-Time Preview
* Creating PDF, HTML, Docbook, ...
* Many Extentions (PlantUML, JavaFX)

https://github.com/asciidocfx/AsciidocFX/releases[Download]


== GitHub Pages with AsciiDoc

Currently, Github Pages cannot render an .adoc (AsciiDoc) file.
To use GitHub Pages with AsciiDoc files we have to convert the adoc files to HTML files. This can simply be done with the command line, see <<Usage>>.


== Links
* https://asciidoctor.org/[Official AsciiDoctor Page]
* https://asciidoctor.org/docs/convert-documents/[How to convert adoc files ]
* https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Cheatsheet (Syntax quick reference)]
* https://www.asciidocfx.com/[AsciidocFx (AsciidocFx)]
* https://pages.github.com/[GitHub Pages] 





